
// Updated listData.js
export const bangalorePropertiesData = [
  {
    id: 1,
    title: "Agricultural Plain Land for Sale",
    img: "/the-eagles-test/properties/agricultural_land.jpg", // Use the appropriate image path
    extent: "0.20 gunta",
    location: "Mysore to Devalapura road",
    distance: "20 km from Mysore",
    village: "Hadinaru",
    road: "20 Km Tar road",
    soil: "Red",
    facing: "West and North",
    plantation: {
      coconut: false,
      arecanut: false,
      mango: true,
      sapota: true,
      pomegranate: true,
      teak: false,
      banana: true,
    },
    fencing: "Fully fenced",
    borewell: false,
    openWell: true,
    farmhouse: true,
    pumpHouse: true,
    cowShed: true,
    pricePerGunta: "5 lakhs per gunta",
    totalPrice: "1 crore for 20 guntas",
  },
  {
    id: 2,
    title: "Commercial Site for Sale",
    img: "/the-eagles-test/properties/commercial_site.jpg", // Use the appropriate image path
    location: "Vijaya Nagara 1st stage",
    layoutName: "Vijaya Nagara 1st stage",
    siteDimension: "50x80",
    siteFacing: "West",
    siteNumber: 423,
    roadWidth: "80 feet",
    mudaAllotted: true,
    mudaApproved: false,
    dtcpApproved: false,
    pricePerSqft: "13,000/- per sqft",
    totalPrice: "5.20 crores",
  },
  {
    id: 3,
    title: "Residential Site for Sale",
    img: "/the-eagles-test/properties/residential_site.jpg", // Use the appropriate image path
    location: "Vijaya Nagara 4th stage",
    layoutName: "Vijaya Nagara 4th stage",
    siteDimension: "40x60",
    siteFacing: "West",
    siteNumber: 1523,
    roadWidth: "40 feet",
    mudaAllotted: true,
    mudaApproved: false,
    dtcpApproved: false,
    pricePerSqft: "6,500/- per sqft",
    totalPrice: "1.56 crores",
  },
  {
    id: 4,
    title: "Residential House for Sale",
    img: "/the-eagles-test/properties/residential_house.jpg", // Use the appropriate image path
    bhk: "3BHK",
    groundFloor: false,
    duplex: true,
    buildersFloor: false,
    area: "Lingabuddi palya, inside Ring road",
    siteDimension: "36×40 = 1440 sqft",
    siteFacing: "North/West corner",
    mainDoorFacing: "East",
    roadWidth: "40 feet",
    mudaAllotted: false,
    mudaApproved: true,
    dtcpApproved: false,
    bedrooms: 3,
    attachBathrooms: 3,
    commonBathroom: 1,
    poojaRoom: 1,
    totalBuiltUpArea: "27 Squares",
    balconies: 1,
    totalFloors: "G + 1",
    semiFurnished: true,
    fullyFurnished: false,
    carParking: "Portico",
    totalPrice: "Rs. 2.10 crores",
  },
  // Add Bangalore location data similarly...
];

export const mysorePropertiesData = [
  {
    id: 1,
    title: "Agricultural Plain Land for Sale",
    img: "/the-eagles-test/properties/agricultural_land.jpg", // Use the appropriate image path
    extent: "0.20 gunta",
    location: "Mysore to Devalapura road",
    distance: "20 km from Mysore",
    village: "Hadinaru",
    road: "20 Km Tar road",
    soil: "Red",
    facing: "West and North",
    plantation: {
      coconut: false,
      arecanut: false,
      mango: true,
      sapota: true,
      pomegranate: true,
      teak: false,
      banana: true,
    },
    fencing: "Fully fenced",
    borewell: false,
    openWell: true,
    farmhouse: true,
    pumpHouse: true,
    cowShed: true,
    pricePerGunta: "5 lakhs per gunta",
    totalPrice: "1 crore for 20 guntas",
  },
  {
    id: 2,
    title: "Commercial Site for Sale",
    img: "/the-eagles-test/properties/commercial_site.jpg", // Use the appropriate image path
    location: "Vijaya Nagara 1st stage",
    layoutName: "Vijaya Nagara 1st stage",
    siteDimension: "50x80",
    siteFacing: "West",
    siteNumber: 423,
    roadWidth: "80 feet",
    mudaAllotted: true,
    mudaApproved: false,
    dtcpApproved: false,
    pricePerSqft: "13,000/- per sqft",
    totalPrice: "5.20 crores",
  },
  {
    id: 3,
    title: "Residential Site for Sale",
    img: "/the-eagles-test/properties/residential_site.jpg", // Use the appropriate image path
    location: "Vijaya Nagara 4th stage",
    layoutName: "Vijaya Nagara 4th stage",
    siteDimension: "40x60",
    siteFacing: "West",
    siteNumber: 1523,
    roadWidth: "40 feet",
    mudaAllotted: true,
    mudaApproved: false,
    dtcpApproved: false,
    pricePerSqft: "6,500/- per sqft",
    totalPrice: "1.56 crores",
  },
  {
    id: 4,
    title: "Residential House for Sale",
    img: "/the-eagles-test/properties/residential_house.jpg", // Use the appropriate image path
    bhk: "3BHK",
    groundFloor: false,
    duplex: true,
    buildersFloor: false,
    area: "Lingabuddi palya, inside Ring road",
    siteDimension: "36×40 = 1440 sqft",
    siteFacing: "North/West corner",
    mainDoorFacing: "East",
    roadWidth: "40 feet",
    mudaAllotted: false,
    mudaApproved: true,
    dtcpApproved: false,
    bedrooms: 3,
    attachBathrooms: 3,
    commonBathroom: 1,
    poojaRoom: 1,
    totalBuiltUpArea: "27 Squares",
    balconies: 1,
    totalFloors: "G + 1",
    semiFurnished: true,
    fullyFurnished: false,
    carParking: "Portico",
    totalPrice: "Rs. 2.10 crores",
  },
  // Add Bangalore location data similarly...
];

  
  export const singlePostData = {
    id: 1,
    title: "Beautiful Apartment",
    price: 1200,
    images: [
      "https://images.pexels.com/photos/1918291/pexels-photo-1918291.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/1428348/pexels-photo-1428348.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/2062426/pexels-photo-2062426.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/2467285/pexels-photo-2467285.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    bedRooms: 2,
    bathroom: 1,
    size: 861,
    latitude: 51.5074,
    longitude: -0.1278,
    city: "London",
    address: "1234 Broadway St",
    school: "250m away",
    bus: "100m away",
    restaurant: "50m away",
    description:
      "Future alike hill pull picture swim magic chain seed engineer nest outer raise bound easy poetry gain loud weigh me recognize farmer bare danger. actually put square leg vessels earth engine matter key cup indeed body film century shut place environment were stage vertical roof bottom lady function breeze darkness beside tin view local breathe carbon swam declared magnet escape has from pile apart route coffee storm someone hold space use ahead sheep jungle closely natural attached part top grain your grade trade corn salmon trouble new bend most teacher range anybody every seat fifteen eventually",
  };
  